version: '3.3'
services:
  db:
    image: postgres:12.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ps_admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: dbdemo
    hostname: dbdemo
    env_file:
      - db.env
    ports:
      - "5432:5432"